"""create all tables

Revision ID: d328975cda4c
Revises: 
Create Date: 2025-09-08 11:24:15.165603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd328975cda4c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thread_qa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thread_qa_id'), 'thread_qa', ['id'], unique=False)
    op.create_index(op.f('ix_thread_qa_label'), 'thread_qa', ['label'], unique=False)
    op.create_index(op.f('ix_thread_qa_session_id'), 'thread_qa', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thread_qa_session_id'), table_name='thread_qa')
    op.drop_index(op.f('ix_thread_qa_label'), table_name='thread_qa')
    op.drop_index(op.f('ix_thread_qa_id'), table_name='thread_qa')
    op.drop_table('thread_qa')
    # ### end Alembic commands ###
